SELECT
    NAME,
    PER_PUPIL_EXPENDITURE
FROM
    DISTRICTS
    JOIN EXPENDITURES
    ON EXPENDITURES.DISTRICT_ID = DISTRICTS.ID
WHERE
    TYPE LIKE '%Public School%'
ORDER BY
    PER_PUPIL_EXPENDITURE DESC LIMIT 10;