SELECT
    SCHOOLS.NAME,
    PER_PUPIL_EXPENDITURE,
    GRADUATED
FROM
    DISTRICTS
    JOIN GRADUATION_RATES
    ON GRADUATION_RATES.SCHOOL_ID = SCHOOLS.ID

    JOIN SCHOOLS
    ON SCHOOLS.DISTRICT_ID = DISTRICTS.ID
    
    JOIN EXPENDITURES
    ON EXPENDITURES.DISTRICT_ID = DISTRICTS.ID
ORDER BY
    PER_PUPIL_EXPENDITURE DESC,
    SCHOOLS.NAME;