SELECT
    TO_USER_ID
FROM
    USERS
    JOIN MESSAGES
    ON MESSAGES.FROM_USER_ID = USERS.ID
WHERE
    USERS.USERNAME = 'creativewisdom377'
GROUP BY
    TO_USER_ID
ORDER BY
    COUNT(TO_USER_ID) DESC LIMIT 3;