CREATE TABLE INGREDIENTS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL,
    PRICE DOUBLE NOT NULL
);

CREATE TABLE DONUTS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL,
    PRICE DOUBLE NOT NULL,
    GLUTEN_FREE TEXT NOT NULL,
    INGREDIENTS_ID,
    FOREIGN KEY (INGREDIENTS_ID) REFERENCES INGREDIENTS (ID)
);

CREATE TABLE ORDERS(
    ORDER_NUMBER INTEGER PRIMARY KEY AUTOINCREMENT,
    DONUT_ID,
    CUSTOMER_ID,
    FOREIGN KEY (DONUT_ID) REFERENCES DONUTS(ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID)
);

CREATE TABLE CUSTOMERS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    FIRST_NAME TEXT NOT NULL,
    LAST_NAME TEXT NOT NULL,
    ORDER_ID,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_NUMBER)
);



