CREATE VIEW BY_DISTRICT AS
    SELECT
        DISTRICT,
        SUM(FAMILIES)   AS FAMILIES,
        SUM(HOUSEHOLDS) AS HOUSEHOLDS,
        SUM(POPULATION) AS POPULATION,
        SUM(MALE)       AS MALES,
        SUM(FEMALE)     AS FEMALES
    FROM
        CENSUS
    GROUP BY
        DISTRICT;