SELECT
    FIRST_NAME,
    LAST_NAME,
    SALARY,
    HR,
    PERFORMANCES.YEAR
FROM
    PLAYERS
    JOIN PERFORMANCES
    ON PERFORMANCES.PLAYER_ID = PLAYERS.ID
    JOIN SALARIES
    ON SALARIES.PLAYER_ID = PLAYERS.ID
ORDER BY
    PLAYERS.ID,
    PERFORMANCES.YEAR,
    HR,
    SALARY;