SELECT
    FIRST_NAME,
    LAST_NAME,
    SALARIES.SALARY,
    PERFORMANCES.HR,
    PERFORMANCES.YEAR
FROM
    PLAYERS
    JOIN PERFORMANCES
    ON PERFORMANCES.PLAYER_ID = PLAYERS.ID
    JOIN SALARIES
    ON SALARIES.PLAYER_ID = PLAYERS.ID
    AND SALARIES.YEAR = PERFORMANCES.YEAR
ORDER BY
    PLAYERS.ID,
    PERFORMANCES.YEAR DESC,
    PERFORMANCES.HR DESC,
    SALARIES.SALARY DESC;