SELECT
    FIRST_NAME,
    LAST_NAME,
    SALARY/H AS 'dollars per hit'
FROM
    PLAYERS
    inner JOIN PERFORMANCES
    ON PERFORMANCES.PLAYER_ID = PLAYERS.ID
    inner JOIN SALARIES
    ON SALARIES.PLAYER_ID = PLAYERS.ID
    and PERFORMANCES.year = salaries.year
WHERE
    PERFORMANCES.YEAR = 2001
    AND SALARY/H IS NOT NULL
ORDER BY
    SALARY/H,
    FIRST_NAME,
    LAST_NAME LIMIT 10;