SELECT
    FIRST_NAME,
    LAST_NAME
FROM
    PLAYERS
    JOIN PERFORMANCES
    ON PERFORMANCES.PLAYER_ID = PLAYERS.ID
    JOIN SALARIES
    ON SALARIES.PLAYER_ID = PLAYERS.ID
WHERE
    PERFORMANCES.YEAR = 2001
    AND SALARY/RBI IS NOT NULL
ORDER BY
    SALARY/RBI,
    FIRST_NAME,
    LAST_NAME LIMIT 10;