SELECT
    FIRST_NAME,
    LAST_NAME,
    SALARY
FROM
    PLAYERS
    JOIN SALARIES
    ON SALARIES.PLAYER_ID = PLAYERS.ID
WHERE
    SALARIES.YEAR = 2001
ORDER BY
    SALARY ASC,
    FIRST_NAME,
    LAST_NAME,
    PLAYERS.ID LIMIT 50;