SELECT
    TEAMS.NAME,
    SUM(H) AS 'total hits'
FROM
    TEAMS
    JOIN PERFORMANCES
    ON PERFORMANCES.TEAM_ID = TEAMS.ID
WHERE
    PERFORMANCES.YEAR = 2001
GROUP BY
    TEAMS.NAME
ORDER BY
    SUM(H) DESC LIMIT 5;