SELECT
    SALARY AS "salary"
FROM
    PERFORMANCES
    JOIN SALARIES
    ON PERFORMANCES.PLAYER_ID = SALARIES.PLAYER_ID
    AND PERFORMANCES.YEAR = SALARIES.YEAR
WHERE
    PERFORMANCES.YEAR = 2001
ORDER BY
    PERFORMANCES.HR DESC LIMIT 1;