SELECT
    HR
FROM
    SALARIES
    JOIN TEAMS
    ON TEAMS.ID = SALARIES.TEAM_ID
    JOIN PERFORMANCES
    ON PERFORMANCES.TEAM_ID = TEAMS.ID
WHERE
    PERFORMANCES.YEAR = 2001
ORDER BY
    HR DESC LIMIT 1;