CREATE VIEW FREQUENTLY_REVIEWED AS
    SELECT
        LISTINGS.ID,
        PROPERTY_TYPE,
        HOST_NAME,
        COUNT(REVIEWS.ID) AS REVIEWS
    FROM
        LISTINGS
        JOIN REVIEWS
        ON REVIEWS.LISTING_ID = LISTINGS.ID
    GROUP BY
        LISTINGS.ID
    ORDER BY
        REVIEWS DESC LIMIT 10;