CREATE VIEW JUNE_VACANCIES AS
    SELECT
        LISTINGS.ID,
        PROPERTY_TYPE,
        HOST_NAME,
        COUNT(AVAILABLE) AS DAYS_VACANT
    FROM
        LISTINGS
        JOIN AVAILABILITIES
        ON AVAILABILITIES.LISTING_ID = LISTINGS.ID
    WHERE
        AVAILABLE IS 'TRUE'
        AND DATE LIKE '2023-06%'
    GROUP BY
        LISTINGS.ID;